### ISSUE TITLE
Comparison with cs3org/charts

### ISSUE THREAD

**Issue by michielbdejong** [sciencemesh/charts#24]
What is the difference between this repo and https://github.com/cs3org/charts ?

**Comment by SamuAlfageme** [comment]
Mentioned in https://github.com/cs3org/charts/issues/38#issuecomment-1210621389. More information can be found in the Section 4: _Reference Deployment_ of the [IOP paper](https://www.epj-conferences.org/articles/epjconf/pdf/2021/05/epjconf_chep2021_02041.pdf)

**Comment by michielbdejong** [comment]
@SamuAlfageme thanks!
CC @navid-dada
